#!/usr/bin/env python3
"""Generate the Swift + CSS + JSON design-token exports from the canonical
Kotlin token module (design doc task T3).

The single semantic source is `core/designsystem/.../theme/tokens/*.kt`. Each
token object carries a `Raw` block of platform-neutral constants; this script
parses those blocks and emits, so the three platforms never drift:

  - CSS custom properties for the web shell  -> composeApp .../resources/design-tokens.css
  - a Swift `SyrmosTokens` enum for iOS       -> injected into DesignSystem/SyrmosColors.swift
                                                 (between generated markers; the project
                                                  lists files individually in pbxproj, so a
                                                  standalone file would not compile)
  - a JSON artifact                           -> core/designsystem/tokens.generated.json

Run from the repo root:  python3 ops/designsystem/generate_tokens.py
"""

from __future__ import annotations
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
TOKENS_DIR = REPO / "core/designsystem/src/commonMain/kotlin/com/syrmos/core/designsystem/theme/tokens"
CSS_OUT = REPO / "composeApp/src/wasmJsMain/resources/design-tokens.css"
SWIFT_OUT = REPO / "iosApp/iosApp/DesignSystem/SyrmosColors.swift"
JSON_OUT = REPO / "core/designsystem/tokens.generated.json"

SWIFT_BEGIN = "// MARK: - Generated design tokens (T3) BEGIN - do not edit, run ops/designsystem/generate_tokens.py"
SWIFT_END = "// MARK: - Generated design tokens (T3) END"

RAW_RE = re.compile(r"object\s+Raw\s*\{(.*?)\n\s*\}", re.S)
CONST_RE = re.compile(r"const\s+val\s+(\w+)\s*=\s*([^\n/]+)")


def parse_raw(kt_path: Path) -> dict[str, str]:
    """Return the {name: rawLiteral} map from a token file's `object Raw`."""
    text = kt_path.read_text()
    m = RAW_RE.search(text)
    if not m:
        return {}
    out: dict[str, str] = {}
    for name, val in CONST_RE.findall(m.group(1)):
        out[name] = val.strip()
    return out


def camel_to_kebab(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "-", name).lower()


def argb_to_rgb_hex(literal: str) -> str:
    """0xFF1466B8 -> #1466B8 (drops the FF alpha; all tokens are opaque)."""
    v = int(literal, 16)
    return f"#{v & 0xFFFFFF:06X}"


def load() -> dict[str, dict[str, str]]:
    files = {
        "color": TOKENS_DIR / "SyrmosColorTokens.kt",
        "spacing": TOKENS_DIR / "SyrmosSpacingTokens.kt",
        "shape": TOKENS_DIR / "SyrmosShapeTokens.kt",
        "motion": TOKENS_DIR / "SyrmosMotionTokens.kt",
        "typography": TOKENS_DIR / "SyrmosTypographyTokens.kt",
    }
    data = {}
    for key, path in files.items():
        if not path.exists():
            sys.exit(f"missing token file: {path}")
        data[key] = parse_raw(path)
    return data


# Color names whose value is the dark override of a base semantic name.
DARK_MAP = {
    "surfaceDark": "surface",
    "surfaceMutedDark": "surfaceMuted",
    "surfaceCardDark": "surfaceCard",
    "onSurfaceDark": "onSurface",
    "onSurfaceMutedDark": "onSurfaceMuted",
    "outlineDark": "outline",
    "brandOnDark": "brand",
    "warningContainerDark": "warningContainer",
}
WEIGHT_NAMES = {"regular", "medium", "semibold", "bold"}

# Semantic aliases are intentionally references, not copied values. The raw
# values remain canonical in the Kotlin token files while every consumer gets
# the same product-facing vocabulary.
SEMANTIC_COLOR_ALIASES = {
    "accent": "brand",
    "accentStrong": "brandStrong",
    "backgroundCanvas": "surface",
    "backgroundSubtle": "surfaceMuted",
    "backgroundRaised": "surfaceCard",
    "textPrimary": "onSurface",
    "textSecondary": "onSurfaceMuted",
    "borderSubtle": "outline",
    "statusPositive": "live",
    "statusInfo": "scheduled",
    "statusNeutral": "offline",
    "statusCaution": "estimated",
    "statusWarning": "warning",
    "statusCritical": "disruption",
}


def build_json(d):
    colors = {}
    for name, lit in d["color"].items():
        colors[name] = argb_to_rgb_hex(lit)
    return {
        "color": colors,
        "spacing": {k: int(v) for k, v in d["spacing"].items()},
        "shape": {k: int(v) for k, v in d["shape"].items()},
        "motion": {k: (float(v.rstrip("f")) if v.endswith("f") else int(v))
                   for k, v in d["motion"].items()},
        "typography": {k: int(v) for k, v in d["typography"].items()},
        "semantic": {
            "color": {
                name: f"{{color.{source}}}"
                for name, source in SEMANTIC_COLOR_ALIASES.items()
            },
        },
    }


def emit_css(d) -> str:
    lines = ["/* GENERATED by ops/designsystem/generate_tokens.py - do not edit. */",
             "/* Canonical source: core/designsystem/.../theme/tokens/*.kt (T3). */",
             ":root {"]
    lines.append("  /* color (light) */")
    dark = {}
    for name, lit in d["color"].items():
        hexv = argb_to_rgb_hex(lit)
        if name in DARK_MAP:
            dark[DARK_MAP[name]] = hexv
            continue
        lines.append(f"  --sy-{camel_to_kebab(name)}: {hexv};")
    lines.append("  /* spacing (px, 8pt grid) */")
    for name, v in d["spacing"].items():
        lines.append(f"  --sy-space-{camel_to_kebab(name)}: {int(v)}px;")
    lines.append("  /* radius */")
    for name, v in d["shape"].items():
        lines.append(f"  --sy-radius-{camel_to_kebab(name)}: {int(v)}px;")
    lines.append("  /* motion */")
    m = d["motion"]
    for name, v in m.items():
        if name.endswith("Ms"):
            lines.append(f"  --sy-{camel_to_kebab(name)}: {int(v)}ms;")
    glide = (f"cubic-bezier({m['glideX1'].rstrip('f')}, {m['glideY1'].rstrip('f')}, "
             f"{m['glideX2'].rstrip('f')}, {m['glideY2'].rstrip('f')})")
    lines.append(f"  --sy-ease-glide: {glide};")
    lines.append("  /* typography */")
    for name, v in d["typography"].items():
        if name in WEIGHT_NAMES:
            lines.append(f"  --sy-weight-{name}: {int(v)};")
        else:
            lines.append(f"  --sy-font-{camel_to_kebab(name)}: {int(v)}px;")
    lines.append("}")
    lines.append("")
    lines.append("body {")
    lines.append("  /* semantic aliases */")
    for name, source in SEMANTIC_COLOR_ALIASES.items():
        lines.append(
            f"  --sy-{camel_to_kebab(name)}: var(--sy-{camel_to_kebab(source)});"
        )
    lines.append("}")
    lines.append("")
    lines.append("/* Dark values follow the app theme toggle, not the OS preference. */")
    lines.append("body.dark-mode {")
    for base, hexv in dark.items():
        lines.append(f"  --sy-{camel_to_kebab(base)}: {hexv};")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def emit_swift(d) -> str:
    L = [SWIFT_BEGIN,
         "// Canonical source: core/designsystem/.../theme/tokens/*.kt.",
         "enum SyrmosTokens {"]
    L.append("    // Colors (light).")
    for name, lit in d["color"].items():
        if name in DARK_MAP:
            continue
        L.append(f"    static let {name} = Color(hex: 0x{int(lit, 16) & 0xFFFFFF:06X})")
    L.append("    enum Dark {")
    for name, lit in d["color"].items():
        if name not in DARK_MAP:
            continue
        L.append(f"        static let {DARK_MAP[name]} = Color(hex: 0x{int(lit, 16) & 0xFFFFFF:06X})")
    L.append("    }")
    L.append("    enum Space {")
    for name, v in d["spacing"].items():
        L.append(f"        static let {name}: CGFloat = {int(v)}")
    L.append("    }")
    L.append("    enum Radius {")
    for name, v in d["shape"].items():
        L.append(f"        static let {name}: CGFloat = {int(v)}")
    L.append("    }")
    L.append("    enum Motion {")
    for name, v in d["motion"].items():
        if name.endswith("Ms"):
            L.append(f"        static let {name} = {int(v)}")
        else:
            L.append(f"        static let {name}: Double = {float(v.rstrip('f'))}")
    L.append("    }")
    L.append("    enum Font {")
    for name, v in d["typography"].items():
        if name in WEIGHT_NAMES:
            continue
        L.append(f"        static let {name}: CGFloat = {int(v)}")
    L.append("    }")
    L.append("}")
    L.append(SWIFT_END)
    return "\n".join(L)


def inject_swift(block: str) -> None:
    text = SWIFT_OUT.read_text()
    if SWIFT_BEGIN in text and SWIFT_END in text:
        pre = text[: text.index(SWIFT_BEGIN)]
        post = text[text.index(SWIFT_END) + len(SWIFT_END):]
        text = pre + block + post
    else:
        text = text.rstrip() + "\n\n" + block + "\n"
    SWIFT_OUT.write_text(text)


def main() -> None:
    d = load()
    CSS_OUT.write_text(emit_css(d))
    JSON_OUT.write_text(json.dumps(build_json(d), indent=2, sort_keys=True) + "\n")
    inject_swift(emit_swift(d))
    n = sum(len(v) for v in d.values())
    print(f"generated {n} tokens -> {CSS_OUT.name}, SyrmosColors.swift block, {JSON_OUT.name}")


if __name__ == "__main__":
    main()
