import Foundation

enum StationIconNames {
    static let m1: [String] = [
        "metro_m1_01_piraeus_pi",
        "metro_m1_02_faliro_fa",
        "metro_m1_03_moschato_mo",
        "metro_m1_04_kallithea_ka",
        "metro_m1_05_tavros_ta",
        "metro_m1_06_petralona_pe",
        "metro_m1_07_thissio_th",
        "metro_m1_08_monastiraki_mo",
        "metro_m1_09_omonia_om",
        "metro_m1_10_victoria_vi",
        "metro_m1_11_attiki_at",
        "metro_m1_12_aghios_nikolaos_an",
        "metro_m1_13_kato_patissia_kp",
        "metro_m1_14_aghios_eleftherios_ae",
        "metro_m1_15_ano_patissia_ap",
        "metro_m1_16_perissos_pe",
        "metro_m1_17_pefkakia_pe",
        "metro_m1_18_nea_ionia_ni",
        "metro_m1_19_iraklio_ir",
        "metro_m1_20_irini_ir",
        "metro_m1_21_neratziotissa_ne",
        "metro_m1_22_maroussi_ma",
        "metro_m1_23_kat_ka",
        "metro_m1_24_kifissia_ki",
    ]
    static let m2: [String] = [
        "metro_m2_01_anthoupoli_an",
        "metro_m2_02_peristeri_pe",
        "metro_m2_03_aghios_antonios_aa",
        "metro_m2_04_sepolia_se",
        "metro_m2_05_attiki_at",
        "metro_m2_06_larissa_station_ls",
        "metro_m2_07_metaxourghio_me",
        "metro_m2_08_omonia_om",
        "metro_m2_09_panepistimio_pa",
        "metro_m2_10_syntagma_sy",
        "metro_m2_11_akropoli_ak",
        "metro_m2_12_sygrou_fix_sf",
        "metro_m2_13_neos_kosmos_nk",
        "metro_m2_14_aghios_ioannis_ai",
        "metro_m2_15_dafni_da",
        "metro_m2_16_aghios_dimitrios_ad",
        "metro_m2_17_ilioupoli_il",
        "metro_m2_18_alimos_al",
        "metro_m2_19_argyroupoli_ar",
        "metro_m2_20_elliniko_el",
    ]
    static let m3: [String] = [
        "metro_m3_01_dimotiko_theatro_dt",
        "metro_m3_02_piraeus_pi",
        "metro_m3_03_maniatika_ma",
        "metro_m3_04_nikea_ni",
        "metro_m3_05_korydallos_ko",
        "metro_m3_06_aghia_varvara_av",
        "metro_m3_07_aghia_marina_am",
        "metro_m3_08_egaleo_eg",
        "metro_m3_09_eleonas_el",
        "metro_m3_10_kerameikos_ke",
        "metro_m3_11_monastiraki_mo",
        "metro_m3_12_syntagma_sy",
        "metro_m3_13_evangelismos_ev",
        "metro_m3_14_megaro_mousikis_mm",
        "metro_m3_15_ambelokipi_am",
        "metro_m3_16_panormou_pa",
        "metro_m3_17_katehaki_ka",
        "metro_m3_18_ethniki_amyna_ea",
        "metro_m3_19_holargos_ho",
        "metro_m3_20_nomismatokopio_no",
        "metro_m3_21_aghia_paraskevi_ap",
        "metro_m3_22_halandri_ha",
        "metro_m3_23_doukissis_plakentias_dp",
        "metro_m3_24_pallini_pa",
        "metro_m3_25_peania_kantza_pk",
        "metro_m3_26_koropi_ko",
        "metro_m3_27_airport_ai",
    ]
    static let t6: [String] = [
        "tram_t6_01_syntagma_sy",
        "tram_t6_02_zappio_za",
        "tram_t6_03_leof_vouliagmenis_lv",
        "tram_t6_04_fix_fi",
        "tram_t6_05_kasomouli_ka",
        "tram_t6_06_neos_kosmos_nk",
        "tram_t6_07_m_mousourou_mm",
        "tram_t6_08_aghios_sostis_as",
        "tram_t6_09_aghia_fotini_af",
        "tram_t6_10_baknana_ba",
        "tram_t6_11_aegeou_ae",
        "tram_t6_12_edem_ed",
        "tram_t6_13_pikrodafni_pi",
    ]
    static let t7: [String] = [
        "tram_t7_01_akti_posidonos_ap",
        "tram_t7_02_aghia_triada_at",
        "tram_t7_03_platia_ippodamias_pi",
        "tram_t7_04_34ou_syntagmatos_34",
        "tram_t7_05_androutsou_an",
        "tram_t7_06_skylitsi_sk",
        "tram_t7_07_s_e_f_se",
        "tram_t7_08_neo_faliro_fa",
        "tram_t7_09_moschato_mo",
        "tram_t7_10_kallithea_ka",
        "tram_t7_11_tzitzifies_tz",
        "tram_t7_12_delta_falirou_df",
        "tram_t7_13_aghia_skepi_as",
        "tram_t7_14_trocadero_tr",
        "tram_t7_15_parko_flisvou_pf",
        "tram_t7_16_flisvos_fl",
        "tram_t7_17_batis_ba",
        "tram_t7_18_edem_ed",
        "tram_t7_19_pikrodafni_pi",
        "tram_t7_20_marina_alimou_ma",
        "tram_t7_21_kalamaki_ka",
        "tram_t7_22_zefyros_ze",
        "tram_t7_23_loutra_alimou_la",
        "tram_t7_24_elliniko_el",
        "tram_t7_25_1st_ag_kosma_k1",
        "tram_t7_26_2nd_ag_kosma_k2",
        "tram_t7_27_aghios_alexandros_aa",
        "tram_t7_28_hellinon_olympionikon_ho",
        "tram_t7_29_kentro_istioploias_ki",
        "tram_t7_30_platia_vergoti_pv",
        "tram_t7_31_paralia_glyfadas_pg",
        "tram_t7_32_paleo_dimarhio_pd",
        "tram_t7_33_platia_katraki_pk",
        "tram_t7_34_angelou_metaxa_am",
        "tram_t7_35_platia_esperidon_pe",
        "tram_t7_36_kolymvitirio_ko",
        "tram_t7_37_asklipiio_voulas_av",
    ]

    /// Suburban A1 (Piraeus to Airport). Asset catalogue ships the
    /// legacy OASA naming "train_p1_*" for this route. We map by
    /// station id rather than by sequence because the published
    /// asset list includes Ano Liosia + SKA stops that aren't on the
    /// current A1 timetable; a strict zip would mis-align everything
    /// after Kato Acharnai.
    static let a1: [String: String] = [
        "A1_PIR": "train_p1_01_piraeus_pi",
        "A1_LEF": "train_p1_02_lefka_le",
        "A1_REN": "train_p1_03_rentis_re",
        "A1_TAV": "train_p1_04_tavros_ta",
        "A1_ROU": "train_p1_05_rouf_ro",
        "A1_ATH": "train_p1_06_athens_at",
        "A1_AAN": "train_p1_07_ag_anargyroi_aa",
        "A1_PYR": "train_p1_08_pyrgos_vasilissis_pv",
        "A1_KAC": "train_p1_09_kato_acharnai_ka",
        "A1_MET": "train_p1_12_metamorfosi_me",
        "A1_IRK": "train_p1_13_irakleio_ir",
        "A1_NER": "train_p1_14_neratziotissa_ne",
        "A1_KIF": "train_p1_15_kifisias_ki",
        "A1_PEN": "train_p1_16_pentelis_pe",
        "A1_DPL": "train_p1_17_doukissis_plakentias_dp",
        "A1_PAL": "train_p1_18_pallini_pa",
        "A1_PEK": "train_p1_19_paiania_kantza_pk",
        "A1_KRP": "train_p1_20_koropi_ko",
        "A1_AER": "train_p1_21_airport_ai",
    ]

    /// Suburban A2 (Ano Liosia to Airport). Assets ship under their
    /// canonical "train_a2_*" prefix and align 1:1 with the timetable.
    static let a2: [String: String] = [
        "A2_ANL": "train_a2_01_ano_liosia_al",
        "A2_ACH": "train_a2_02_acharnai_railway_center_ac",
        "A2_MET": "train_a2_04_metamorfosi_me",
        "A2_IRK": "train_a2_05_irakleio_ir",
        "A2_NER": "train_a2_06_neratziotissa_ne",
        "A2_KIF": "train_a2_07_kifisias_ki",
        "A2_PEN": "train_a2_08_pentelis_pe",
        "A2_DPL": "train_a2_09_doukissis_plakentias_dp",
        "A2_PAL": "train_a2_10_pallini_pa",
        "A2_PEK": "train_a2_11_peania_kantza_pk",
        "A2_KRP": "train_a2_12_koropi_ko",
        "A2_AER": "train_a2_13_airport_ai",
    ]

    /// Suburban A3 (Athens to Chalcis). Asset prefix "train_p3_*".
    static let a3: [String: String] = [
        "A3_ATH": "train_p3_01_athens_at",
        "A3_AAN": "train_p3_02_ag_anargyroi_aa",
        "A3_ACH": "train_p3_03_ska_sk",
        "A3_AXN": "train_p3_04_acharnes_ac",
        "A3_DEK": "train_p3_05_dekeleia_de",
        "A3_AST": "train_p3_06_agios_stefanos_as",
        "A3_AFI": "train_p3_07_afidnes_af",
        "A3_SFE": "train_p3_08_sfendali_sf",
        "A3_AVL": "train_p3_09_avlonas_av",
        "A3_ATH2": "train_p3_10_agios_thomas_at",
        "A3_OIN": "train_p3_11_oinofyta_oi",
        "A3_OIN2": "train_p3_12_oinoi_oi",
        "A3_DIL": "train_p3_13_dilesi_di",
        "A3_AGE": "train_p3_14_agios_georgios_ag",
        "A3_KAL": "train_p3_15_kalochori_panteichi_kp",
        "A3_AUL": "train_p3_16_avlida_av",
        "A3_CHA": "train_p3_17_chalkida_ch",
    ]

    /// Suburban A4 (Piraeus to Kiato). Asset prefix "train_p2_*".
    static let a4: [String: String] = [
        "A4_PIR": "train_p2_01_piraeus_pi",
        "A4_LEF": "train_p2_02_lefka_le",
        "A4_REN": "train_p2_03_rentis_re",
        "A4_TAV": "train_p2_04_tavros_ta",
        "A4_ROU": "train_p2_05_rouf_ro",
        "A4_ATH": "train_p2_06_athens_at",
        "A4_AAN": "train_p2_07_ag_anargyroi_aa",
        "A4_PYR": "train_p2_08_pyrgos_vasilissis_pv",
        "A4_KAC": "train_p2_09_kato_acharnai_ka",
        "A4_ZEF": "train_p2_10_zefyri_ze",
        "A4_ANL": "train_p2_11_ano_liosia_al",
        "A4_ASP": "train_p2_12_aspropyrgos_as",
        "A4_MAG": "train_p2_13_magoula_ma",
        "A4_NEP": "train_p2_14_nea_peramos_np",
        "A4_MEG": "train_p2_15_megara_me",
        "A4_KIN": "train_p2_16_kineta_ki",
        "A4_AGT": "train_p2_17_ag_theodoroi_th",
        "A4_KOR": "train_p2_18_korinthos_ko",
        "A4_ZEV": "train_p2_19_zevgolatio_ze",
        "A4_KIA": "train_p2_20_kiato_ki",
    ]
}
