package com.syrmos.core.model.transit

data class LiveSuburbanTrain(
    val id: String,
    val lineId: String,
    val trainNumber: String,
    val origin: String?,
    val destination: String?,
    val nextStation: String?,
    val delayMinutes: Int,
    val serviceType: String,
    val progress: Double?,
    val speedKph: Double?,
    val latitude: Double,
    val longitude: Double,
    val updatedAt: String,
    val course: Double? = null,
    val altitude: Double? = null,
    val locomotiveNumber: String? = null,
    val distanceToDestination: Int? = null,
    val distanceToNextStation: Int? = null,
    val signalStatus: String? = null,
    val corridor: String? = null,
    val trainType: String? = null,
    val scheduledDeparture: String? = null,
    val scheduledArrival: String? = null,
    val scheduleStatus: String? = null,
    val trainId: String? = null,
    val liveStreamUrl: String? = null,
)
